compiler:
 - gcc

git:
 submodules: false

language: cpp
sudo: required
dist: xenial

os: 
 - linux

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

branches:
  only:
    - master
    - unstable

before_install:
    - eval "${MATRIX_EVAL}"
install:
    - echo Building everything
    - bash scripts/build.sh 

script:
    - bash scripts/test_client.sh 128x128 5 3600 8000000000 10000 10 18.46,38.16 2019/09/01-00:11:26.$RANDOM$RANDOM | vlbi_client_dummy 
