compiler:
 - gcc

git:
 submodules: false

language: cpp
sudo: required
dist: xenial

os: 
 - linux

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

branches:
  only:
    - master
    - unstable

before_install:
    - eval "${MATRIX_EVAL}"
install:
    - echo Building everything
    - bash scripts/build.sh 

script:
    - bash scripts/test.sh 3600 geo_synthesis_dft | vlbi_client_dummy -h 16 | base64 -d -i | convert -size 128x128 -depth 8 -colorspace GRAY gray:- png:- | display
