compiler:
 - gcc

git:
 submodules: false

language: cpp
sudo: required
dist: xenial

os: 
 - linux

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

branches:
  only:
    - master
    - unstable

before_install:
    - eval "${MATRIX_EVAL}"
install:
    - echo Building everything
    - bash scripts/build.sh 

script:
    - scripts/test_client.sh 5 7200 8000000000 1 2.46,38.16 | vlbi_client_dummy
