version: 2

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/OpenVLBI
    steps:
      - checkout
      - run:
          name: build
          command: |
            ./scripts/build.sh
            mkdir -p tests
            vlbi_client_json -t 1 -f scripts/coverage.json | jq .plot.buffer | tr -d '"' | base64 -d | convert -size 1024x1024 -depth 8 GRAY:- tests/synthesis_delay_coverage.png
            vlbi_client_json -t 1 -f scripts/raw.json | jq .plot.buffer | tr -d '"' | base64 -d | convert -size 1024x1024 -depth 8 GRAY:- tests/synthesis_delay_raw.png
            vlbi_client_json -t 1 -f scripts/idft.json | jq .plot.buffer | tr -d '"' | base64 -d | convert -size 1024x1024 -depth 8 GRAY:- tests/synthesis_delay_idft.png

workflows:
  version: 2
  build:
    jobs:
      - build
