version: 2

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: build
          command: ./scripts/build.sh

workflows:
  version: 2
  build:
    jobs:
      - build
