version: 2

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/OpenVLBI
    steps:
      - checkout
      - run:
          name: build
          command: |
            sudo add-apt-repository ppa:~mutlaqja/ppa
            sudo apt-get update
            sudo apt-get install indi-full libindi-dev cdbs cmake build-essential fakeroot devscripts
            cd ../; tar zcvf libopenvlbi_$(head -n OpenVLBI/debian/changelog | tr -d [a-z:\(:\):=:\;:\ ]).orig.tar.gz OpenVLBI; cd OpenVLBI; dpkg-buildpackage;
            sudo dpkg -i ../libopenvlbi_$(head -n 1 debian/changelog | tr -d [a-z:\(:\):=:\;:\ ]).deb
            sudo dpkg -i ../openvlbi-bin_$(head -n 1 debian/changelog | tr -d [a-z:\(:\):=:\;:\ ]).deb
            ./scripts/test.sh 1000 synthesis_coverage | vlbi_client_dummy
workflows:
  version: 2
  build:
    jobs:
      - build
