version: 2

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/OpenVLBI
    steps:
      - checkout
      - run:
          name: build
          command: |
            ./scripts/build.sh
            pushd scripts; ./test.sh 1000 synthesis_coverage | vlbi_client_dummy; popd

workflows:
  version: 2
  build:
    jobs:
      - build
