version: 2

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: build
          command: |
             scripts/build.sh
             ./scripts/test.sh 1000 synthesis_coverage | vlbi_client_dummy
workflows:
  version: 2
  build:
    jobs:
      - build
