
name: Linux
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Get Sources
        uses: actions/checkout@v2
        with:
          path: 'OpenVLBI'

      - name: Build & Install
        run: |
            cd OpenVLBI
            ./scripts/build.sh

      - name: Run Tests
        run: |
            mkdir -p tests
            vlbi_client_json -t 1 -f scripts/coverage.json | jq .plot.buffer | tr -d '"' | base64 -d | convert -size 1024x1024 -depth 8 GRAY:- tests/synthesis_delay_coverage.png
            vlbi_client_json -t 1 -f scripts/raw.json | jq .plot.buffer | tr -d '"' | base64 -d | convert -size 1024x1024 -depth 8 GRAY:- tests/synthesis_delay_raw.png
            vlbi_client_json -t 1 -f scripts/idft.json | jq .plot.buffer | tr -d '"' | base64 -d | convert -size 1024x1024 -depth 8 GRAY:- tests/synthesis_delay_idft.png

      - name: Debs
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: OpenVLBI/packages

      - name: Tests
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: OpenVLBI/tests
