
name: Linux
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: debian-latest

    strategy:
      fail-fast: false

    steps:
      - name: Get Sources
        uses: actions/checkout@v2
        with:
          path: 'OpenVLBI'

      - name: Build & Install
        run: |
            cd OpenVLBI
            ./scripts/build.sh

      - name: Run Tests
        run: |
            cd OpenVLBI
            mkdir -p tests
            scripts/json_to_png.sh scripts/coverage.json tests/synthesis_delay_coverage.png
            scripts/json_to_png.sh scripts/raw.json tests/synthesis_delay_raw.png
            scripts/json_to_png.sh scripts/idft.json tests/synthesis_delay_idft.png

      - name: Debs
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: OpenVLBI/packages

      - name: Tests
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: OpenVLBI/tests
